# K-Nearest Neighbors (Bangladesh Diabetes Prediction)

## Penjelasan

### Tujuan

Untuk membuat model machine learning yang dapat memprediksi apakah suatu pasien menderita diabetes atau tidak melalui data yang telah disediakan.

### Penjelasan Kolom

- ***Age (Usia)*** = Usia pasien dalam tahun.
- ***Gender (Jenis Kelamin)*** = Jenis kelamin pasien (Pria/Wanita).
- ***Polyuria*** = Frekuensi buang air kecil yang berlebihan (Ya/Tidak).
- ***Polydipsia*** = Rasa haus yang berlebihan (Ya/Tidak).
- ***Sudden weight loss (Penurunan berat badan mendadak)*** = Penurunan berat badan yang tiba-tiba tanpa sebab jelas
(Ya/Tidak).
- ***Weakness (Kelemahan)*** = Perasaan lemah atau lelah yang tidak biasa (Ya/Tidak).
- ***Polyphagia*** = Nafsu makan yang meningkat secara berlebihan (Ya/Tidak).
- ***Genital thrush (Infeksi jamur genital)*** = Adanya infeksi jamur pada area genital (Ya/Tidak).
- ***Visual blurring (Penglihatan kabur)*** = Gangguan penglihatan seperti penglihatan kabur (Ya/Tidak).
- ***Itching (Gatal-gatal)*** = Rasa gatal pada kulit tanpa sebab yang jelas (Ya/Tidak).
- ***Irritability (Iritabilitas)*** = Perasaan mudah marah atau tersinggung (Ya/Tidak).
- ***Delayed healing (Penyembuhan luka lambat)*** = Luka yang membutuhkan waktu lebih lama untuk sembuh (Ya/Tidak).
- ***Partial paresis (Paresis parsial)*** = Kelemahan otot sebagian atau kelumpuhan ringan (Ya/Tidak).
- ***Muscle stiffness (Kekakuan otot)*** = Kekakuan atau ketegangan pada otot (Ya/Tidak).
- ***Alopecia*** = Kehilangan rambut atau kebotakan (Ya/Tidak).
- ***Obesity (Obesitas)*** = Kondisi kelebihan berat badan atau obesitas (Ya/Tidak).
- ***Class*** = Klasifikasi apakah pasien menderita diabetes atau tidak (Positif/Negatif).

## A. Data Preparation

### A.1 Import Libraries

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### A.2 Load Data

In [2]:
try:
    df = pd.read_csv('bangladesh_diabetes.csv')
    print('Berhasil Membaca Data')
except Exception as e:
    print('Gagal Membaca Data')

Berhasil Membaca Data

### A.3 Melihat Dimensi Data

In [3]:
df.shape

(520, 17)

### A.4 Melihat Informasi Data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

### A.5 Melihat Statistik Data

#### Sebelum Mapping

In [5]:
df.describe().T.style.format('{:.2f}').background_gradient(cmap='flare')

#### Sesudah Mapping

### A.6 Melihat 5 Data Teratas dan 5 Data Terbawah

In [10]:
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

In [7]:
df.tail()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

### A.7 Melihat Data Duplikat

In [11]:
df.duplicated().sum()

np.int64(269)

### A.8 Melihat Data Hilang

In [12]:
df.isna().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

### A.9 Melihat Data Outlier

## B. Data Preprocessing